### ISSUE TITLE
Trial Setup can visit any path in docker container

### ISSUE THREAD

**Issue by Snax1210** [pipech/erpnext-docker-debian#122]

**Comment by Snax1210** [comment]
![image](https://user-images.githubusercontent.com/31029217/160526986-d7e5ce66-9d9e-4263-ac45-66d5b3243bad.png)

**Comment by Snax1210** [comment]
How to close the file access permission

**Comment by pipech** [comment]
Oh wow, I didn't know we can do that, I can replicate this error from this url `http://localhost:8000/../../../../../../../../../../../../etc/passwd`

Site got serve by [`gunicorn`](https://github.com/frappe/frappe/blob/c3009392d80d533da31975199a5a08a872519552/frappe/app.py#L291-L326)

But how to prevent this, I'm not sure.

May I ask why do you want to fix this since trial setup are meant to be developing and testing setup.

Already testing it on production setup, we can't do this in production, so rest assured.

**Comment by Snax1210** [comment]
Because the erpnext only use to LAN , I didn't config the `site_domain` parameter , production setup has Nginx, I will install Nginx to repair it , THANKS.
