### ISSUE TITLE
frappe container won't start

### ISSUE THREAD

**Issue by jottunn** [pipech/erpnext-docker-debian#36]
Hi,

Am trying out your production deployment but the frappe container doesn't start, it just recreates itself indefinitely.

I ran a container based on    pipech/erpnext-docker-debian:mas-py3-latest via "docker run" and executed the entrypoint_prd.sh script to see what's up, here is the output:
`frappe@7e3a43243e9c:~/production_config$ . entrypoint_prd.sh 

++ benchWD=/home/frappe
++ cd /home/frappe/production_config
++ sudo cp common_site_config_docker.json /home/frappe/bench/sites/common_site_config.json
++ sudo cp supervisor.conf /etc/supervisor/conf.d/supervisor.conf
++ sudo -E /bin/bash -c 'envsubst '\''$NGINX_SERVER_NAME'\'' < nginx.temp > /etc/nginx/conf.d/default.conf'
/bin/bash: envsubst: command not found`

gettext isn't present in the image, is that the problem or am I missing something?

**Comment by stapeldev** [comment]
First of all, great solution. Thank you for creating this. Looking a lot through the forums it's clear that many of the challenges with ERPNext revolve around deployment. This is a critical solution for bringing the wonderful ERPNext ecosystem to a broader audience.  

Not sure if this is related, but when I run the latest version of the stack, during the creation of the stack, on the container task for the Frappe container, the "command" is failing with a permission denied error. I realize @jottunn is running the container with the docker run command, but it seems like perhaps there is a relationship because the error I see is happening during the same process.

>  level=error msg="fatal task error" error="starting container failed: OCI runtime create failed: container_linux.go:344: starting container process caused \"exec: \\\"/home/frappe/production_config/entrypoint_prd.sh\\\": permission denied\": unknown" module=node/agent/taskmanager

It's also possible this is something specific to my environment, so take it for what it's worth. As a side note, did not have this problem with the "Stable" image prior to the latest version release.

**Comment by pipech** [comment]
Hi, @stapeldev 

It is most likely that your error doesn't relate to jottunn.

I've update image to fixed your problem by adding `sudo chmod +x /home/$systemUser/production_config/entrypoint_prd.sh` to Dockerfile and it should fixed this problem.

Building log is here https://travis-ci.com/pipech/erpnext-docker-debian/builds/99782569
After image has been push it should take about 25 mins and build should be pass.

You can try to pull newer image and run it again to see if it fixed your problem.

If it works I strongly recommend you to change frappe image tag in prd.yml from `mas-py3-latest` to specific image version ie. `11.1.4-py3` or version you desire. To prevent accidentally update new frappe version.

PS. `mas-py3-latest` image is on version 11, `stable` image is on version 10.
If you want to stay on version 10 you could use `v10-py2-latest` or see list of all available image here https://hub.docker.com/r/pipech/erpnext-docker-debian/tags

PS2. `stable` tag doesn't mean it is more stable than `mas-py3-latest`, it is just a old tag I used when I manually test if image is useable.

**Comment by stapeldev** [comment]
@pipech thanks for the quick response. You are correct, I did a bit more digging into my environment and the problem was missing execute permissions on "conf" folder in my cloned version. Not sure how that happened. As a note, for me, adding  "sudo apt-get -y install gettext-base" to the entrypoint_prd.sh file did resolve the same reported issue from the @jottunn. 

Thanks again and I will try the updated image with the recommended tag of 11.1.4-py3.  Again, thanks for your work on this, great stuff!

**Comment by jottunn** [comment]
thanks for readding apt install gettext in the Dockerfile, putting in the entrypoint script was kind of spaghettiish

**Comment by bmelman** [comment]
This is still happening when following Production-Setup with image:pipech/erpnext-docker-debian:v12-py3-latest .
No matter how I alter conf/frappe-docker-conf/entrypoint_prd.sh, it keeps starting a version without gettext, and/or my alterations. How do i get  conf/frappe-docker-conf/entrypoint_prd.sh into my container?

**Comment by pipech** [comment]
Re added "gettext".

https://github.com/pipech/erpnext-docker-debian/blob/8bf5f4d45d7c1b73b73dba49cc9ce27e66fc085b/Dockerfile#L174
