### ISSUE TITLE
production setup - domain really required?

### ISSUE THREAD

**Issue by vrms** [pipech/erpnext-docker-debian#46]
in the [instructions for the production setup](https://github.com/pipech/erpnext-docker-debian/blob/master/docs/setup/production_setup.md) it says
> _This setup is meant to run on server with public IP address **and domain pointing to those IP address**, otherwise it won’t work._

I am wondering whether the _**"domain pointing to those IP addresses"**_ part is actually correct. I mean you should be able to access your ERPNext instance directly via the IP addresse as well, wouldn't you?

**Comment by pipech** [comment]
**"domain pointing to those IP addresses"** part is meant that you have to set A record of domain name to server IP address.

This is needed for setting up HTTPS by Let's encrypt from Traefik container.

> I mean you should be able to access your ERPNext instance directly via the IP addresse as well, wouldn't you?

In this setup you couldn't access ERPNext instance using IP address since this setup use DNS based multi-tenancy.

You could access your ERPNext instance directly via the IP address but you have to disable Multi-tenant first.

**Comment by vrms** [comment]
> You could access your ERPNext instance directly via the IP address but you have to disable Multi-tenant first.

that would be entering the frappe container & running `bench config dns_multitenant off`, correct?

**Comment by pipech** [comment]
> that would be entering the frappe container & running `bench config dns_multitenant off`, correct?

Yes, and you have to config traefik to redirect ip-address to frappe container (or remove traefik and add port 80 to frappe container and directly access frappe container)

https://github.com/pipech/erpnext-docker-debian/issues/44#issuecomment-468208892

**Comment by pipech** [comment]
Close due to inactivity, feel free to reopen if you have more question.

**Comment by SuperJuke** [comment]
I disbled multitenancy and mapped port 80 to an external port. But all I get is the default Nginx page. How do I access the ERPNext site?
