### ISSUE TITLE
Confused about tag version numbers

### ISSUE THREAD

**Issue by JohnVeness** [pipech/erpnext-docker-debian#99]
Looking in https://hub.docker.com/r/pipech/erpnext-docker-debian/tags I am confused what the tag number represents. Going back in time, looking at just the 12.x tags, we have:

- 12.8.1
- 12.7.3
- 12.7.2

which seem to correspond to frappe releases.

*But* the next oldest tags are 12.9.4, 12.9.3, which sound more like erpnext version numbers. Which is it supposed to be?

**Comment by pipech** [comment]
It's the one with higher version number.

ie. frappe 12.9.1 and erpnext 12.9.6, image tag will be 12.9.6

**Comment by JohnVeness** [comment]
Thanks. I'm not sure I understand, though. I'm trying to find the latest v12 version of your docker image, and am not sure which to use.

**Comment by pipech** [comment]
I just check, I think image tagging script doesn't work properly.

https://travis-ci.com/github/pipech/erpnext-docker-debian/jobs/363367158

This image just build and it's `{'erpnext': {'version_str': '12.10.1', 'version_list': ['12', '10', '1']}, 'frappe': {'version_str': '12.8.1', 'version_list': ['12', '8', '1']}}`
Instead of using 12.10.1 as image version it use 12.8.1

I'll fix this.

**Comment by JohnVeness** [comment]
Many thanks for looking into this. Hope you manage to fix. I must say that it's annoying that frappe and erpnext have different version numbers to start with, but that's not your fault!

Maybe you should force the script to always use the erpnext version number?

**Comment by pipech** [comment]
Fixed the script.

I'll keep that in mind but I won't change script to use erpnext version number for now, part of the reason is I'm lazy but another reason for why I using this script in the first place is we don't know for sure that erpnext will always have higher version number and by fixing it to erpnext will make image tag won't get update if frappe have higher version number.

Thank you for taking interest in this project.
Cheers !

**Comment by JohnVeness** [comment]
Thanks for fixing :)

I understand what you're saying. You could maybe use *both* version numbers in the image tag, e.g. erpnextver-frappever. So 12.10.1-12.8.1 for example. A bit long-winded, but should cope with all possible updating scenarios, I think.

Another possibility would be for us to lobby Frappe to always keep the two version numbers the same!

**Comment by pipech** [comment]
> Another possibility would be for us to lobby Frappe to always keep the two version numbers the same!
I don't think this will ever happen. Haha

But the idea of having both version is nice, i might implement this. Don't know why I never thought of this.

**Comment by pipech** [comment]
Tag version semantic

**12-F10.1_E14.3-py3**

 - Frappe version 12.10.1
 - ERPNext version 12.14.3
 - Python3

I've updated tag version semantic per your suggestion. It'll be easier to understand.
Thank you for your suggestion.

Cheers !

**Comment by JohnVeness** [comment]
Thanks!
